### ISSUE TITLE
In english

### ISSUE THREAD

**Issue by algenty** [korbinzhao/mxgraph-editor#1]
Hi,

I creating grafana plugin based on mxgraph.
I try to integrate an editor, i found you project but i cant understand chinese.
How to put it in english ?

Best regards,
Arnaud

**Comment by korbinjoe** [comment]
Hi,

I have supported english in newest commit. 
Thanks for suggestion. 
If have any other question, please issue it, I will respond as soon as possible.

Best regards,
Korbin

**Comment by algenty** [comment]
Thx Korbin
I ll try it

**Comment by algenty** [comment]
its work
Nice work !
Congratulation 🥇
