### ISSUE TITLE
Issue with Save function

### ISSUE THREAD

**Issue by renjithsraj** [korbinzhao/mxgraph-editor#2]
Hi I have tried your demo functionality with mxgraph-editor, It's really awesome. but when I click Save function nothing is happening, can you please update. save and open functionalities.

**Comment by korbinjoe** [comment]
Thx for issuing this problem. I have update the save event function in demo. You can pull the newest code from master branch, and see the demo code in './demo/toolbar.jsx'. @renjithsraj

**Comment by renjithsraj** [comment]
Thanks for your support, ut when I run again, it's shows like the data(diagram data in save) as Null. the screen shot is attached plz help for save and open funcitonalities.
![none](https://user-images.githubusercontent.com/8171465/54571256-e1800200-4a07-11e9-8797-f80ff0f0df52.png)

**Comment by korbinjoe** [comment]
did you pull the newest code from master? it is ok just like below picture show.

every change in graph will trigger the callback function autoSaveFunc, u can get the diagram data in this function too.

![image](https://user-images.githubusercontent.com/5051627/54582176-c1bdfd80-4a4a-11e9-8038-6e398df9ce97.png)

![image](https://user-images.githubusercontent.com/5051627/54582379-7526f200-4a4b-11e9-9603-11856a6f17b0.png)

![image](https://user-images.githubusercontent.com/5051627/54582408-94258400-4a4b-11e9-90fa-9f5346a299f7.png)
