### ISSUE TITLE
following the tutorial, but got an error after `npm start`

### ISSUE THREAD

**Issue by litaotao** [korbinzhao/mxgraph-editor#3]
following the tutorial, but got an error after `npm start`

<img width="553" alt="屏幕快照 2019-05-07 下午6 13 36" src="https://user-images.githubusercontent.com/4660350/57292236-e6059480-70f3-11e9-83d0-b59bf45b25ec.png">

**Comment by korbinjoe** [comment]
@litaotao do you run "npm install" successfully? the problem cannot reproduce on my computer.
