### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by algenty** [korbinzhao/mxgraph-editor#5]
Hi @korbinzhao,
I contacted you a few months ago to translate your work in english.
I wanted to thank you personally because thanks to you, I finally managed to release my grafana plugin based on mxgraph :
https://github.com/algenty/grafana-flowcharting

Thx a lot

**Comment by korbinjoe** [comment]
@algenty It is my pleasure to be of some help. grafana-flowcharting is a wonderful plugin.
